### ISSUE TITLE
Coordinated cross-country data repository on NPIs

### ISSUE THREAD

**Issue by joachim-gassen** [seabbs/CovidInterventionReview#20]
Hi there:

Sorry for jumping on this and feel free to close the issue if you deem it to be inappropriate. But given that you seem to work on effects of NPI I wonder whether you are aware of any coordinated efforts to construct a cross country data repository for Covid-19 related NPIs? I have opened an issue about it [here](https://github.com/CSSEGISandData/COVID-19/issues/1393).

Thank you!

Joachim

**Comment by Imai-N** [comment]
A couple of resources that might be useful:

https://data.humdata.org/dataset/oxford-covid-19-government-response-tracker
and
https://data.humdata.org/dataset/acaps-covid19-government-measures-dataset

**Comment by joachim-gassen** [comment]
Thank you! I have been working with those in the meantime. Just in case if you are interested, [here is a blog post](https://joachim-gassen.github.io/2020/04/exploring-and-benchmarking-oxford-government-response-data/) where I compare both of them in terms of quality.

Thanks again. I am closing the issue.
